chore(deps): Bump spring-boot-starter-parent from 2.7.13 to 2.7.14 (#710)
Bumps [spring-boot-starter-parent](https://togithub.com/spring-projects/spring-boot) from 2.7.13 to 2.7.14.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://togithub.com/spring-projects/spring-boot/releases">spring-boot-starter-parent's releases</a>.</em></p>
<blockquote>
<h2>v2.7.14</h2>
<h2>:lady_beetle: Bug Fixes</h2>
<ul>
<li>Only one health group can be exposed using management.endpoint.health.group.xxx.additional-path=server:/newpath when using Jersey <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36250">#36250</a></li>
<li>MockitoPostProcessor doesn't check FactoryBean.OBJECT_TYPE_ATTRIBUTE correctly <a href="https://redirect.github.com/spring-projects/spring-boot/pull/36224">#36224</a></li>
<li>ConfigurationPropertiesReportEndpoint does not display primitive wrapper types <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36076">#36076</a></li>
<li>When using Flyway 9.20.0, auto-configuration fails with a NoSuchMethodError due to the removal of Oracle-related methods from FluentConfiguration <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36029">#36029</a></li>
<li>Saml2RelyingPartyRegistrationConfiguration can choose the wrong RelyingPartyRegistration.Builder when using a metadata file with multiple providers <a href="https://redirect.github.com/spring-projects/spring-boot/pull/35902">#35902</a></li>
<li>ImportsContextCustomizer does not support AliasFor <a href="https://redirect.github.com/spring-projects/spring-boot/pull/34917">#34917</a></li>
<li>ConfigurationPropertyName#equals is not symmetric when element has trailing dashes <a href="https://redirect.github.com/spring-projects/spring-boot/pull/34804">#34804</a></li>
</ul>
<h2>:notebook_with_decorative_cover: Documentation</h2>
<ul>
<li>Add Javadoc since to ImageReference.inTaglessForm() <a href="https://redirect.github.com/spring-projects/spring-boot/pull/36048">#36048</a></li>
<li>Polish Kafka Properties Docs <a href="https://redirect.github.com/spring-projects/spring-boot/pull/36032">#36032</a></li>
<li>Fix typo in the Using R2DBC section of the reference documentation <a href="https://redirect.github.com/spring-projects/spring-boot/pull/36019">#36019</a></li>
<li>Improve Kubernetes liveness and readiness probes customization documentation <a href="https://redirect.github.com/spring-projects/spring-boot/pull/34978">#34978</a></li>
<li>Document auto-configuration of underlying HTTP client when using WebClient or RestTemplate <a href="https://redirect.github.com/spring-projects/spring-boot/issues/34136">#34136</a></li>
</ul>
<h2>:hammer: Dependency Upgrades</h2>
<ul>
<li>Upgrade to Elasticsearch 7.17.11 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36311">#36311</a></li>
<li>Upgrade to Groovy 3.0.18 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36312">#36312</a></li>
<li>Upgrade to Janino 3.1.10 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36313">#36313</a></li>
<li>Upgrade to Johnzon 1.2.21 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36314">#36314</a></li>
<li>Upgrade to Micrometer 1.9.13 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36171">#36171</a></li>
<li>Upgrade to Neo4j Java Driver 4.4.12 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36315">#36315</a></li>
<li>Upgrade to Rabbit AMQP Client 5.14.3 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36316">#36316</a></li>
<li>Upgrade to Reactor Bom 2020.0.34 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36172">#36172</a></li>
<li>Upgrade to Spring AMQP 2.4.14 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36399">#36399</a></li>
<li>Upgrade to Spring Data Bom 2021.2.14 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36173">#36173</a></li>
<li>Upgrade to Spring Framework 5.3.29 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36174">#36174</a></li>
<li>Upgrade to Spring HATEOAS 1.5.5 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36413">#36413</a></li>
<li>Upgrade to Spring Security 5.7.10 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36295">#36295</a></li>
<li>Upgrade to Tomcat 9.0.78 <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36317">#36317</a></li>
</ul>
<h2>:heart: Contributors</h2>
<p>Thank you to all the contributors who worked on this release:</p>
<p><a href="https://togithub.com/ThomazPassarelli"><code>@​ThomazPassarelli</code></a>, <a href="https://togithub.com/bbulgarelli"><code>@​bbulgarelli</code></a>, <a href="https://togithub.com/bedla"><code>@​bedla</code></a>, <a href="https://togithub.com/dependabot"><code>@​dependabot</code></a>[bot], <a href="https://togithub.com/dkswnkk"><code>@​dkswnkk</code></a>, <a href="https://togithub.com/eydunn"><code>@​eydunn</code></a>, <a href="https://togithub.com/garyrussell"><code>@​garyrussell</code></a>, <a href="https://togithub.com/izeye"><code>@​izeye</code></a>, <a href="https://togithub.com/lasselindqvist"><code>@​lasselindqvist</code></a>, <a href="https://togithub.com/lmartelli"><code>@​lmartelli</code></a>, and <a href="https://togithub.com/quaff"><code>@​quaff</code></a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/e538ddb3655fa742400324bfb4f4fb91db420315"><code>e538ddb</code></a> Release v2.7.14</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/7ec9f45929d09238654602a21c58e15f1856940d"><code>7ec9f45</code></a> Upgrade to Spring Security 5.7.10</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/250868ad849f206fbc79fd2ed8a9aa7048e08618"><code>250868a</code></a> Upgrade to Spring AMQP 2.4.14</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/08054cf3802a99f6f28cb30db0a739bb1a9c635a"><code>08054cf</code></a> Merge pull request <a href="https://redirect.github.com/spring-projects/spring-boot/issues/36062">#36062</a> from quaff</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/09e5d38348bedffbc711cd874a3891bc12cc5534"><code>09e5d38</code></a> Polish &quot;Replace <a href="https://togithub.com/CsvSource"><code>@​CsvSource</code></a> with <a href="https://togithub.com/ValueSource"><code>@​ValueSource</code></a> where feasible&quot;</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/acb7acd5d954cfa2798cc2ce0fe477e509f4bfa2"><code>acb7acd</code></a> Replace <a href="https://togithub.com/CsvSource"><code>@​CsvSource</code></a> with <a href="https://togithub.com/ValueSource"><code>@​ValueSource</code></a> where feasible</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/beb4010d073a9a4ea7289176734389608570c8f4"><code>beb4010</code></a> Upgrade to Spring HATEOAS 1.5.5</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/67bae9de36ac054d547a4bdfd1d9cc1506a0bf28"><code>67bae9d</code></a> Upgrade to Spring Data Bom 2021.2.14</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/1c5567340578e5c0b39281c5f7dfea9cc205585a"><code>1c55673</code></a> Upgrade CI to Docker 24.0.4</li>
<li><a href="https://togithub.com/spring-projects/spring-boot/commit/b3513b5d89c14db5e819f56d7b7b4272542a87b7"><code>b3513b5</code></a> Start building against Spring AMQP 2.4.14 snapshots</li>
<li>Additional commits viewable in <a href="https://togithub.com/spring-projects/spring-boot/compare/v2.7.13...v2.7.14">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.springframework.boot:spring-boot-starter-parent&package-manager=maven&previous-version=2.7.13&new-version=2.7.14)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>